version: '3.4'

services:
  api:
    image: docker.ub.gu.se/rails:ruby-3.2.2
    volumes:
      - ${OPENHOURS_REPO}:/usr/src/app
  db:
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
