version: '3.4'
services:
  api:
    image: docker.ub.gu.se/openhours:{$GIT_REVISION}
    restart: always
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${RAILS_SECRET_KEY_BASE} # Not used in development
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    ports:
      - "${EXPOSED_PORT_API}:${RAILS_PORT}"
    volumes:                  # Only for development
      - ${OPENHOURS_REPO}:/usr/src/app    # Only for development
    depends_on:
      - db
  db:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "${EXPOSED_PORT_DB}:${DB_PORT}"
    volumes:
      - ${PWD:-.}/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data # Change dbdata to ${DB_DIR} when not for development
